spring:
   datasource:
      url: "jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
      username: "test"
      password: "test"


#动态多数据源开启配置
#mframe:
#  dynamic:
#    datasource:
#      enable: true

#spring:
#   datasource:
#      druid:
#        master:
#          url: "jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
#          username: "test"
#          password: "test"
#        slaves[0]:
#          url: "jdbc:mysql://127.0.0.1:3306/testdb-slave?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
#          username: "root"
#          password: "root"
#        slaves[1]:
#          url: "jdbc:mysql://127.0.0.1:3306/testdb-slave-1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
#          username: "test"
#          password: "test"

# mongo
mframe:
  mongodb:
    uri: mongodb://test:test@127.0.0.1:40000,127.0.0.1:40001/testdb?replicaSet=mongo
  # 配置oauth权限忽略
  oauth:
    ignore:
      urls:
       - /swagger-resources/**
       - /swagger-ui.html
       - /**/v2/api-docs
       - /swagger/api-docs
