#spring:
#   datasource:
#      url: "jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
#      username: "test"
#      password: "test"
mframe:
  dynamic:
    datasource:
      enable: true

spring:
   datasource:
      druid:
        url: "jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
        master:
          username: "test"
          password: "test"
